# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      NAO\CoreBundle\Entity\User: plaintext

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main_provider:
        entity:
          class: NAOCoreBundle:User
          property: username

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        pattern: ^/
        anonymous: ~
        provider: main_provider
        form_login:
          login_path: nao_core_login
          check_path: nao_core_login_check
        logout:
          path: nao_core_logout
          target: /

    access_control:
      - { path: ^/account$, roles: [ROLE_USER, ROLE_ADMIN] }
